services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test
  - deploy

test_app:
  stage: test
  image: node:latest
  script:
    - npm i --production=false
    - npx prisma migrate reset --schema=./models/schema.prisma -f
    - npx prisma db pull --schema=./models/schema.prisma
    - npx prisma generate --schema=./models/schema.prisma
    - npx jest --runTestsByPath=tests
  only:
    - master
    - main

heroku_deploy:
  stage: deploy
  needs: [test_app]
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master
    - main
